apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: java-jenkins-1211 
  janus-idp.io/tekton: java-jenkins-1211
  backstage.io/kubernetes-id: java-jenkins-1211
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: java-jenkins-1211
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  