apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: java-jenkins-1211-gitops
  description: This is GitOps manifest for java-jenkins-1211   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: java-jenkins-1211
    backstage.io/kubernetes-id: java-jenkins-1211 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: java-jenkins-1211-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:java-jenkins-1211
