apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: java-jenkins-1211
  janus-idp.io/tekton: java-jenkins-1211
  backstage.io/kubernetes-id: java-jenkins-1211
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: java-jenkins-1211
resources:
- deployment.yaml
- route.yaml
- service.yaml
